(** MASC Protobuf Module Coverage Tests

    Tests for autogenerated protobuf types:
    - Empty type
    - Agent type
    - Task type
    - Roundtrip serialization
*)

open Alcotest

module Masc_pb = Masc_mcp.Masc_pb

(* ============================================================
   Empty Tests
   ============================================================ *)

let test_empty_make () =
  let e = Masc_pb.Masc.V1.Empty.make () in
  check unit "empty make" () e

let test_empty_name () =
  let n = Masc_pb.Masc.V1.Empty.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   Agent Tests
   ============================================================ *)

let test_agent_make_default () =
  let a = Masc_pb.Masc.V1.Agent.make () in
  check string "default name" "" a.name;
  check string "default status" "" a.status

let test_agent_make_with_values () =
  let a = Masc_pb.Masc.V1.Agent.make
    ~name:"claude"
    ~status:"active"
    ~capabilities:["code"; "review"]
    () in
  check string "name" "claude" a.name;
  check string "status" "active" a.status;
  check int "capabilities count" 2 (List.length a.capabilities)

let test_agent_name () =
  let n = Masc_pb.Masc.V1.Agent.name () in
  check bool "has name" true (String.length n > 0)

let test_agent_merge () =
  let a1 = Masc_pb.Masc.V1.Agent.make ~name:"a1" () in
  let a2 = Masc_pb.Masc.V1.Agent.make ~status:"active" () in
  let merged = Masc_pb.Masc.V1.Agent.merge a1 a2 in
  (* Merge behavior: later values override *)
  check string "merged status" "active" merged.status

(* ============================================================
   Task Tests
   ============================================================ *)

let test_task_make_default () =
  let t = Masc_pb.Masc.V1.Task.make () in
  check string "default id" "" t.id;
  check string "default status" "" t.status

let test_task_make_with_values () =
  let t = Masc_pb.Masc.V1.Task.make
    ~id:"task-001"
    ~title:"Fix bug"
    ~status:"pending"
    ~priority:1
    () in
  check string "id" "task-001" t.id;
  check string "title" "Fix bug" t.title;
  check int "priority" 1 t.priority

let test_task_name () =
  let n = Masc_pb.Masc.V1.Task.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   BroadcastRequest Tests
   ============================================================ *)

let test_broadcast_request_make () =
  let br = Masc_pb.Masc.V1.BroadcastRequest.make
    ~agent_name:"claude"
    ~message:"Hello world"
    () in
  check string "agent_name" "claude" br.agent_name;
  check string "message" "Hello world" br.message

let test_broadcast_request_name () =
  let n = Masc_pb.Masc.V1.BroadcastRequest.name () in
  check bool "has name" true (String.length n > 0)

(* ============================================================
   Proto Roundtrip Tests
   ============================================================ *)

let test_agent_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.Agent.make
    ~name:"test-agent"
    ~status:"active"
    ~capabilities:["cap1"; "cap2"]
    ~last_heartbeat:"2024-01-15T12:00:00Z"
    ~joined_at:"2024-01-15T10:00:00Z"
    () in
  let writer = Masc_pb.Masc.V1.Agent.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.Agent.from_proto reader with
  | Ok decoded ->
    check string "name roundtrip" original.name decoded.name;
    check string "status roundtrip" original.status decoded.status
  | Error _ -> fail "proto decode failed"

let test_task_proto_roundtrip () =
  let original = Masc_pb.Masc.V1.Task.make
    ~id:"task-123"
    ~title:"Test task"
    ~status:"pending"
    ~priority:2
    () in
  let writer = Masc_pb.Masc.V1.Task.to_proto original in
  let bytes = Ocaml_protoc_plugin.Writer.contents writer in
  let reader = Ocaml_protoc_plugin.Reader.create bytes in
  match Masc_pb.Masc.V1.Task.from_proto reader with
  | Ok decoded ->
    check string "id roundtrip" original.id decoded.id;
    check string "title roundtrip" original.title decoded.title
  | Error _ -> fail "proto decode failed"

(* ============================================================
   Test Runners
   ============================================================ *)

let () =
  run "MASC Protobuf Coverage" [
    "empty", [
      test_case "make" `Quick test_empty_make;
      test_case "name" `Quick test_empty_name;
    ];
    "agent", [
      test_case "make default" `Quick test_agent_make_default;
      test_case "make with values" `Quick test_agent_make_with_values;
      test_case "name" `Quick test_agent_name;
      test_case "merge" `Quick test_agent_merge;
    ];
    "task", [
      test_case "make default" `Quick test_task_make_default;
      test_case "make with values" `Quick test_task_make_with_values;
      test_case "name" `Quick test_task_name;
    ];
    "broadcast_request", [
      test_case "make" `Quick test_broadcast_request_make;
      test_case "name" `Quick test_broadcast_request_name;
    ];
    "proto_roundtrip", [
      test_case "agent" `Quick test_agent_proto_roundtrip;
      test_case "task" `Quick test_task_proto_roundtrip;
    ];
  ]
